[build]
builder = "nixpacks"

[deploy]
startCommand = "npx prisma migrate deploy && echo 'Migrations complete, starting application...' && node dist/main.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"