[build]
builder = "nixpacks"

[deploy]
startCommand = "npx prisma generate && npx prisma migrate deploy && node dist/main.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"