services:
  - type: web
    name: zestquiz-backend
    env: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    buildCommand: docker build -t zestquiz-backend .
    startCommand: docker run -p $PORT:3001 zestquiz-backend 