/**
 * @typedef {Object} User
 * @property {string} id - The user's unique identifier
 * @property {string} email - The user's email address
 * @property {string} username - The user's username
 * @property {'admin' | 'user'} role - The user's role
 * @property {string} createdAt - When the user was created
 * @property {string} updatedAt - When the user was last updated
 */

/**
 * @typedef {Object} Quiz
 * @property {string} id - The quiz's unique identifier
 * @property {string} title - The quiz title
 * @property {string} description - The quiz description
 * @property {string[]} tags - Array of quiz tags
 * @property {'active' | 'inactive' | 'draft'} status - The quiz status
 * @property {boolean} isAIGenerated - Whether the quiz was generated by AI
 * @property {string} createdById - ID of the admin who created the quiz
 * @property {string} createdAt - When the quiz was created
 * @property {string} updatedAt - When the quiz was last updated
 */

/**
 * @typedef {Object} Question
 * @property {string} id - The question's unique identifier
 * @property {string} quizId - The associated quiz ID
 * @property {string} text - The question text
 * @property {number} orderIndex - The question's order in the quiz
 * @property {string} createdAt - When the question was created
 * @property {string} updatedAt - When the question was last updated
 */

/**
 * @typedef {Object} Option
 * @property {string} id - The option's unique identifier
 * @property {string} questionId - The associated question ID
 * @property {string} text - The option text
 * @property {boolean} isCorrect - Whether this is the correct answer
 * @property {number} orderIndex - The option's order in the question
 * @property {string} createdAt - When the option was created
 * @property {string} updatedAt - When the option was last updated
 */

/**
 * @typedef {Object} QuizAttempt
 * @property {string} id - The attempt's unique identifier
 * @property {string} userId - The user who took the quiz
 * @property {string} quizId - The quiz that was taken
 * @property {number} score - The user's score
 * @property {string} startedAt - When the attempt was started
 * @property {string} submittedAt - When the attempt was submitted
 */

/**
 * @typedef {Object} UserAnswer
 * @property {string} id - The answer's unique identifier
 * @property {string} attemptId - The associated quiz attempt ID
 * @property {string} questionId - The associated question ID
 * @property {string} selectedOptionId - The option the user selected
 * @property {boolean} isCorrect - Whether the answer was correct
 * @property {string} answeredAt - When the answer was submitted
 */ 